server:
  port: 8768
spring:
  application:
    name: service-ribbon-feign
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8763/eureka/,http://peer3:8764/eureka/
debug: true
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream