server:
  port: 8769
spring:
  application:
    name: service-zuul

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8763/eureka/,http://localhost:8764/eureka/

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: service-ribbon
    api-b:
      path: /api-b/**
      serviceId: service-ribbon-feign

  host:
    connection-request-timeout-millis: 60000
    socket-timeout-millis: 60000

debug: true
